// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Organization *organization
	Position     *position
	Product      *product
	ProductType  *productType
	Role         *role
	User         *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Organization = &Q.Organization
	Position = &Q.Position
	Product = &Q.Product
	ProductType = &Q.ProductType
	Role = &Q.Role
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Organization: newOrganization(db, opts...),
		Position:     newPosition(db, opts...),
		Product:      newProduct(db, opts...),
		ProductType:  newProductType(db, opts...),
		Role:         newRole(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Organization organization
	Position     position
	Product      product
	ProductType  productType
	Role         role
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Organization: q.Organization.clone(db),
		Position:     q.Position.clone(db),
		Product:      q.Product.clone(db),
		ProductType:  q.ProductType.clone(db),
		Role:         q.Role.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Organization: q.Organization.replaceDB(db),
		Position:     q.Position.replaceDB(db),
		Product:      q.Product.replaceDB(db),
		ProductType:  q.ProductType.replaceDB(db),
		Role:         q.Role.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Organization IOrganizationDo
	Position     IPositionDo
	Product      IProductDo
	ProductType  IProductTypeDo
	Role         IRoleDo
	User         IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Organization: q.Organization.WithContext(ctx),
		Position:     q.Position.WithContext(ctx),
		Product:      q.Product.WithContext(ctx),
		ProductType:  q.ProductType.WithContext(ctx),
		Role:         q.Role.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
